//
// Created by Ryan on 17/08/2025.
//

#ifndef ARDUINO_WIFI_BATTLESHIPS_NETWORKMANAGER_H
#define ARDUINO_WIFI_BATTLESHIPS_NETWORKMANAGER_H


class NetworkManager
{
};


#endif //ARDUINO_WIFI_BATTLESHIPS_NETWORKMANAGER_H